In [40]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [41]:
import numpy as np

In [42]:
np. __version__

'2.3.5'

In [43]:
pyton_list = [1,2,3,"string",6,7]

numlist = [x for x in range(10)]
numlist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
print(numlist*3)
print(type(numlist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [45]:
arri = np.array([1,2,3,4,5])
print(arri)

[1 2 3 4 5]


In [46]:
print(arri*3)
print(type(arri))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [47]:
arr1D = np.array([1, 2, 3])
print(arr1D)

[1 2 3]


In [48]:
arr2D = np.array([[1, 2, 3],
                 [1, 2, 3]])
print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [49]:
arr3D = np.array([[[1, 2, 3],[1, 2, 3]],
                 [[1, 2, 3],[1, 2, 3]]])
print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [50]:
x = np.array([])
type(x)

numpy.ndarray

In [51]:
# ndim works on objects amd checks their dimensions

print(f"dimension are: {arr1D.ndim}")

print(f"dimension are: {arr2D.ndim}")

print(f"dimension are: {arr3D.ndim}")

#using np.shape method, for checking the dimension of an array
#(row,columns)
print(f"dimension are: {np.shape(arr1D)}")

print(f"dimension are: {np.shape(arr2D)}")

print(f"dimension are: {np.shape(arr3D)}")

#size, how 
#

arr1D.dtype

dimension are: 1
dimension are: 2
dimension are: 3
dimension are: (3,)
dimension are: (2, 3)
dimension are: (2, 2, 3)


dtype('int64')

In [52]:
shape1D = arr1D.ndim
shape1D

size1D = arr1D.size
size1D

shape2D = arr2D.ndim
shape2D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D


12

In [53]:
print(arr1D)

[1 2 3]


In [54]:
#broadcasting

arr1D * 30

arr1D + arr1D

array([2, 4, 6])

In [55]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([10,20,30,40,50])
print(arr2)

print("Result: ",arr1 ** arr2)

[1 2 3 4 5]
[10 20 30 40 50]
Result:  [                   1              1048576      205891132094649
                    0 -6776596920136667815]


In [58]:
arr1 = np.array([1,2,3])
print(arr1)

arr2 = np.array([10,20,30])
print(arr2)

print("Result: ",arr1 ** arr2)

[1 2 3]
[10 20 30]
Result:  [              1         1048576 205891132094649]


In [56]:
a = 10
b = 3
print(a +b) #Addition: 13


13


In [57]:
3**30


205891132094649

In [62]:
prices = np.array([4000000,3500000,2500000])
print(f"The prices are: {prices/1000000} million") #scale data

The prices are: [4.  3.5 2.5] million


In [ ]:
- slicing
- reshaping

In [ ]:
# only list comprehension we have used
nums = [x for x in range(0,101,2)]
print(nums)

nums.size 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
# accesing element in list
nums1 = nums[100:0:-1]

# it cahng list to array
arraynums = np.array(nums)
print(arraynums[:])

# it change the arrangement
print(arraynums[100:25:-1])

# it change the arrangement
print(arraynums[:2])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]
[0 2]


In [87]:
# value are evenly spaced and stored in array
line = np.linspace(0,1,10)
line

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# question:-
# the result should be this:
# [0 0.1 0.2 0.3 0.4 .....]

line2 = np.linspace(0,1,11)
print(line2)

In [ ]:
np.zeros((3,3))
np.ones((4,3))

#take in tuple of shape, and return

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [124]:
# random numbers # it will be change every time you run it
# random class in numpy
# numbers
np.random.seed(41)

# randomArray = np.random.rand(3,4)
# randomArray

randomArray = np.random.randint(0,101,(3,3)) #start, stop,(shape)
randomArray


array([[64, 35, 12],
       [98, 80, 65],
       [89, 23, 85]], dtype=int32)

change and reshape and
transform, linear algebra

In [147]:
flatArray = randomArray.flatten()
flatArray


array([64, 35, 12, 98, 80, 65, 89, 23, 85], dtype=int32)

In [148]:
reshapedArray = flatArray.reshape(2,3)
reshapedArray


ValueError: cannot reshape array of size 9 into shape (2,3)

In [123]:
reshapeArray.T

NameError: name 'reshapeArray' is not defined

In [128]:
# aggregations

data = np.array([85,94,22,68,94,54,98]) #marks

# sum
# mean 
# sin max

print(data.sum())

515


In [ ]:
# create a list to 10
# use list comprehension
# give the additions of numbers from 1 to 10

In [129]:
data1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(data1.sum())

55


In [133]:
data1 = [d for d in range(1,11)]
print(data1)

total = sum(data1)
total

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


55

In [143]:
array_idrees = np.array([num for num in range(1,11)])
sum_of_array_idrees = array_idrees.sum()
print(sum_of_array_idrees)
mean_of_array_idrees = array_idrees.mean()
print(mean_of_array_idreesarray_idrees)

# list comprehension - [number:expression]

55


NameError: name 'mean_of_array_idreesarray_idrees' is not defined

Whole thing:
but we can also go, column wise
or row wise

In [155]:
a_2d_matrix = np.ones((3,5))
print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [158]:
# column wise sum

a_2d_matrix.sum(axis=0)

a_2d_matrix.sum(axis=1) # row wise sum

array([5., 5., 5.])

In [ ]:
#arange
# easiest wat to create an array quickly

range_of_number = np.arange(1,11)
range_of_number.reshape(5,2)
print(range_of_number)


# exectly same as this
range_example = np.arange(1,11).reshape(5,2)
print(range_example)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Splitting numpy arrays

In [175]:
dataset_array = np.arange(1,101).reshape(50,2)
#print(dataset_array)

# x ------> y
# 1 ------> 2
# rows are so

train_dataset = dataset_array[:25] # 10 rows
test_dataset = dataset_array[25:] # All the rows
print(test_dataset)

[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
